### ISSUE TITLE
Crashed on startup

### ISSUE THREAD

**Issue by geekishor** [nitinagg1/android-video-listing-mvp#2]
I downloaded and run the app. I get this error.

`09-11 18:57:04.541 28228-28320/com.mn2square.videolistingmvp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                               Process: com.mn2square.videolistingmvp, PID: 28228
                                                                               java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                   at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                                   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                                   at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                   at java.lang.Thread.run(Thread.java:818)
                                                                                Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/video/media from pid=28228, uid=10720 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
                                                                                   at android.os.Parcel.readException(Parcel.java:1620)
                                                                                   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
                                                                                   at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
                                                                                   at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
                                                                                   at android.content.ContentResolver.query(ContentResolver.java:491)
                                                                                   at android.content.CursorLoader.loadInBackground(CursorLoader.java:64)
                                                                                   at android.content.CursorLoader.loadInBackground(CursorLoader.java:56)
                                                                                   at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
                                                                                   at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
                                                                                   at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
                                                                                   at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                                   at java.util.concurrent.FutureTask.run`

**Comment by fastestdevalive** [comment]
Seems like you haven't given the permission for reading the storage. Can you confirm?

**Comment by nitinagg1** [comment]
Yes.. Go to settings and get it..
I should mention in the notes.
