### ISSUE TITLE
[App Crash] while accessing some filenames

### ISSUE THREAD

**Issue by fastestdevalive** [nitinagg1/android-video-listing-mvp#3]
Error in the line:
#113 [FolderListAdapter.java](https://github.com/nitinagg1/android-video-listing-mvp/blob/master/app/src/main/java/com/mn2square/videolistingmvp/swipetabfragments/adapters/FolderListAdapter.java#113)
```  
String folderPath =  group_title.substring(0,lastIndexOf);
```

``` E  FATAL EXCEPTION: main
                         E  Process: com.mn2square.videolistingmvp, PID: 19082
                         E  java.lang.StringIndexOutOfBoundsException: String index out of range: -1
                         E      at java.lang.String.substring(String.java:1975)
                         E      at com.mn2square.videolistingmvp.swipetabfragments.adapters.FolderListAdapter.getGroupView(FolderListAdapter.java:113)
                         E      at android.widget.ExpandableListConnector.getView(ExpandableListConnector.java:446)
                         E      at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
                         E      at android.widget.AbsListView.obtainView(AbsListView.java:2365)
                         E      at android.widget.ListView.makeAndAddView(ListView.java:2052)
                         E      at android.widget.ListView.fillDown(ListView.java:786)
                         E      at android.widget.ListView.fillFromTop(ListView.java:847)
                         E      at android.widget.ListView.layoutChildren(ListView.java:1798)
                         E      at android.widget.AbsListView.onLayout(AbsListView.java:2164)
                         E      at android.view.View.layout(View.java:19659)
                         E      at android.view.ViewGroup.layout(ViewGroup.java:6075)
                         E      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
                         E      at android.view.View.layout(View.java:19659)
                         E      at android.view.ViewGroup.layout(ViewGroup.java:6075)
                         E      at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1799)
                         E      at android.view.View.layout(View.java:19659)
                         E      at android.view.ViewGroup.layout(ViewGroup.java:6075)
                         E      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                         E      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                         E      at android.view.View.layout(View.java:19659)
                         E      at android.view.ViewGroup.layout(ViewGroup.java:6075)
                         E      at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1142)
                         E      at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:836)
                         E      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:850)
                         E      at android.view.View.layout(View.java:19659)
                         E      at android.view.ViewGroup.layout(ViewGroup.java:6075)
                         E      at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                         E      at android.view.View.layout(View.java:19659)
                         E      at android.view.ViewGroup.layout(ViewGroup.java:6075)
                         E      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                         E      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                         E      at android.view.View.layout(View.java:19659)
                         E      at android.view.ViewGroup.layout(ViewGroup.java:6075)
                         E      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                         E      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                         E      at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                         E      at android.view.View.layout(View.java:19659)
                         E      at android.view.ViewGroup.layout(ViewGroup.java:6075)
                         E      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                         E      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                         E      at android.view.View.layout(View.java:19659)
                         E      at android.view.ViewGroup.layout(ViewGroup.java:6075)
                         E      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
                         E      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
                         E      at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
                         E      at android.view.View.layout(View.java:19659)
                         E      at android.view.ViewGroup.layout(ViewGroup.java:6075)
                         E      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
                         E      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
                         E      at com.android.internal.policy.DecorView.onLayout(DecorView.java:761)
                         E      at android.view.View.layout(View.java:19659)
                         E      at android.view.ViewGroup.layout(ViewGroup.java:6075)
                         E      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)
                         E      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)
                         E      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
                         E      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
                         E      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                         E      at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                         E      at android.view.Choreographer.doFrame(Choreographer.java:658)
                         E      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                         E      at android.os.Handler.handleCallback(Handler.java:790)
                         E      at android.os.Handler.dispatchMessage(Handler.java:99)
                         E      at android.os.Looper.loop(Looper.java:164)
                         E      at android.app.ActivityThread.main(ActivityThread.java:6494)
                         E      at java.lang.reflect.Method.invoke(Native Method)
                         E      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                         E      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)```

**Comment by gaurav414u** [comment]
@nitinagg1 Whats the status on this one?
